# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake

# The command to remove a file.
RM = /apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/e802756/COURSES/SSPP/2022-2023/solutions

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/e802756/COURSES/SSPP/2022-2023/solutions

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(CMAKE_COMMAND) -E cmake_progress_start /scratch/e802756/COURSES/SSPP/2022-2023/solutions/CMakeFiles /scratch/e802756/COURSES/SSPP/2022-2023/solutions/matvec/CMakeFiles/progress.marks
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/e802756/COURSES/SSPP/2022-2023/solutions/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
matvec/CMakeFiles/matrix_vector_cublas.dir/rule:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/CMakeFiles/matrix_vector_cublas.dir/rule
.PHONY : matvec/CMakeFiles/matrix_vector_cublas.dir/rule

# Convenience name for target.
matrix_vector_cublas: matvec/CMakeFiles/matrix_vector_cublas.dir/rule

.PHONY : matrix_vector_cublas

# fast build rule for target.
matrix_vector_cublas/fast:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f matvec/CMakeFiles/matrix_vector_cublas.dir/build.make matvec/CMakeFiles/matrix_vector_cublas.dir/build
.PHONY : matrix_vector_cublas/fast

# Convenience name for target.
matvec/CMakeFiles/matrix_vector_2d_block.dir/rule:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/CMakeFiles/matrix_vector_2d_block.dir/rule
.PHONY : matvec/CMakeFiles/matrix_vector_2d_block.dir/rule

# Convenience name for target.
matrix_vector_2d_block: matvec/CMakeFiles/matrix_vector_2d_block.dir/rule

.PHONY : matrix_vector_2d_block

# fast build rule for target.
matrix_vector_2d_block/fast:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f matvec/CMakeFiles/matrix_vector_2d_block.dir/build.make matvec/CMakeFiles/matrix_vector_2d_block.dir/build
.PHONY : matrix_vector_2d_block/fast

# Convenience name for target.
matvec/CMakeFiles/matrix_vector_1thread.dir/rule:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/CMakeFiles/matrix_vector_1thread.dir/rule
.PHONY : matvec/CMakeFiles/matrix_vector_1thread.dir/rule

# Convenience name for target.
matrix_vector_1thread: matvec/CMakeFiles/matrix_vector_1thread.dir/rule

.PHONY : matrix_vector_1thread

# fast build rule for target.
matrix_vector_1thread/fast:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f matvec/CMakeFiles/matrix_vector_1thread.dir/build.make matvec/CMakeFiles/matrix_vector_1thread.dir/build
.PHONY : matrix_vector_1thread/fast

# Convenience name for target.
matvec/CMakeFiles/matrix_vector_1d_block.dir/rule:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f CMakeFiles/Makefile2 matvec/CMakeFiles/matrix_vector_1d_block.dir/rule
.PHONY : matvec/CMakeFiles/matrix_vector_1d_block.dir/rule

# Convenience name for target.
matrix_vector_1d_block: matvec/CMakeFiles/matrix_vector_1d_block.dir/rule

.PHONY : matrix_vector_1d_block

# fast build rule for target.
matrix_vector_1d_block/fast:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(MAKE) -f matvec/CMakeFiles/matrix_vector_1d_block.dir/build.make matvec/CMakeFiles/matrix_vector_1d_block.dir/build
.PHONY : matrix_vector_1d_block/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... matrix_vector_cublas"
	@echo "... matrix_vector_2d_block"
	@echo "... rebuild_cache"
	@echo "... matrix_vector_1thread"
	@echo "... matrix_vector_1d_block"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /scratch/e802756/COURSES/SSPP/2022-2023/solutions && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

